// /app/api/tickets/signature/route.ts - NEW FILE
import { NextRequest, NextResponse } from 'next/server'
import { ethers } from 'ethers'
import { connectDB } from '@/lib/database/connection'
import { GaslessApproval } from '@/lib/database/models'

export const dynamic = 'force-dynamic'

export async function POST(request: NextRequest) {
  try {
    console.log('🔐 [SIGNATURE API] Generating approval signature')
    
    const body = await request.json()
    const { 
      recipient, 
      eventId, 
      ticketCategory = 0, 
      amount = 1, 
      price = '0', 
      validUntil,
      approvalId: providedApprovalId 
    } = body

    // Validate required fields
    if (!recipient || !eventId) {
      return NextResponse.json({
        success: false,
        error: 'Missing required fields: recipient, eventId'
      }, { status: 400 })
    }

    await connectDB()

    // Use the existing generateApprovalId function logic
    const timestamp = Date.now().toString(36)
    const random = Math.random().toString(36).substring(2, 10)
    const approvalId = providedApprovalId || `approval_${timestamp}_${random}`
    
    // Calculate validUntil (default: 1 hour from now)
    const calculatedValidUntil = validUntil || Math.floor(Date.now() / 1000) + 3600
    
    // Check if GASLESS_PRIVATE_KEY is configured
    const GASLESS_PRIVATE_KEY = process.env.GASLESS_PRIVATE_KEY
    
    let signature: string
    let signedBy: string | undefined
    
    if (GASLESS_PRIVATE_KEY) {
      try {
        // Setup wallet with the gasless private key
        const wallet = new ethers.Wallet(GASLESS_PRIVATE_KEY)
        
        // Generate message hash (matching contract's MintApproval struct)
        const messageHash = ethers.solidityPackedKeccak256(
          ['address', 'uint256', 'uint8', 'uint256', 'uint256', 'uint256', 'bytes32'],
          [
            recipient,
            BigInt(eventId),
            Number(ticketCategory),
            BigInt(amount || 1),
            typeof price === 'string' ? ethers.parseEther(price) : BigInt(price),
            BigInt(calculatedValidUntil),
            approvalId
          ]
        )
        
        // Sign the message
        signature = await wallet.signMessage(ethers.getBytes(messageHash))
        signedBy = wallet.address
        console.log('✅ Real signature generated by:', wallet.address)
        
      } catch (signingError) {
        console.error('Signing error:', signingError)
        // Fallback to mock signature
        signature = '0x' + '00'.repeat(65)
        console.warn('⚠️ Using mock signature due to signing error')
      }
    } else {
      // Use mock signature for development
      signature = '0x' + '00'.repeat(65)
      console.warn('⚠️ GASLESS_PRIVATE_KEY not configured, using mock signature')
    }

    // Save approval to database
    const approval = new GaslessApproval({
      approvalId,
      signature,
      recipient,
      validUntil: new Date(calculatedValidUntil * 1000),
      eventId, // This should be the on-chain event ID
      amount,
      price: typeof price === 'string' ? ethers.parseEther(price) : price,
      currency: 'USD',
      status: 'pending',
      metadata: {
        eventOnChainId: eventId,
        ticketCategory,
        generatedAt: new Date().toISOString(),
        signedBy: signedBy || 'mock',
        isMockSignature: !GASLESS_PRIVATE_KEY
      },
      createdAt: new Date(),
      updatedAt: new Date()
    })
    
    await approval.save()
    console.log('✅ Approval saved to database:', approvalId)
    
    return NextResponse.json({
      success: true,
      signature,
      signatureData: {
        recipient,
        eventId,
        ticketCategory,
        amount,
        price,
        validUntil: calculatedValidUntil,
        id: approvalId
      },
      signedBy,
      isMockSignature: !GASLESS_PRIVATE_KEY,
      message: 'Signature generated successfully'
    })

  } catch (error: any) {
    console.error('❌ Signature API error:', error)
    
    return NextResponse.json({
      success: false,
      error: 'Failed to generate signature',
      details: error.message,
      code: error.code
    }, { status: 500 })
  }
}

export async function GET() {
  return NextResponse.json({
    success: true,
    message: 'Signature API endpoint',
    endpoint: 'POST /api/tickets/signature',
    description: 'Generate gasless minting approval signatures'
  })
}